[2024-11-06T00:00:00.310+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T00:00:00.325+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-05T23:59:40.472366+00:00 [queued]>
[2024-11-06T00:00:00.331+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-05T23:59:40.472366+00:00 [queued]>
[2024-11-06T00:00:00.332+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-06T00:00:00.349+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-11-05 23:59:40.472366+00:00
[2024-11-06T00:00:00.353+0000] {standard_task_runner.py:72} INFO - Started process 62 to run task
[2024-11-06T00:00:00.356+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-11-05T23:59:40.472366+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpyg8n1dzw']
[2024-11-06T00:00:00.358+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask s3_upload
[2024-11-06T00:00:00.395+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-05T23:59:40.472366+00:00 [running]> on host 3a2fdfeb3856
[2024-11-06T00:00:00.457+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Swapnil Deshpande' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T23:59:40.472366+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T23:59:40.472366+00:00'
[2024-11-06T00:00:00.459+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T00:00:00.469+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 6, in upload_s3_pipeline
    file_path = ti.xcom_pull(task_id = 'reddit_extraction', key = 'return_value')
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-11-06T00:00:00.478+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-11-05T23:59:40.472366+00:00, execution_date=20241105T235940, start_date=20241106T000000, end_date=20241106T000000
[2024-11-06T00:00:00.489+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T00:00:00.490+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task s3_upload (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 62)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 6, in upload_s3_pipeline
    file_path = ti.xcom_pull(task_id = 'reddit_extraction', key = 'return_value')
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-11-06T00:00:00.529+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-06T00:00:00.559+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T00:00:00.566+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
